unsecuredEndpoints: info, health, prometheus, env

management:
  endpoints:
    web:
      exposure:
        include: ${unsecuredEndpoints}

    jmx:
      exposure:
        include: ${unsecuredEndpoints}
  metrics:
    export:
      jmx:
        domain: com.skyou.metrics

server:
  port: ${PORT:8080}